services:
  pool:
    build:
      context: .
      dockerfile: Dockerfile.pool
    image: qbxpool:latest
    pull_policy: always
    container_name: qbxpool
    ports:
      - "3333:3333"
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped

  miner:
    build:
      context: .
      dockerfile: Dockerfile.miner
    image: miner:latest
    pull_policy: always
    container_name: miner
    depends_on:
      - pool
    entrypoint: ["/bin/miner", "qbxpool:3333", "worker.001"]
