# syntax=docker/dockerfile:1

FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/qbxpool ./cmd/pool

FROM alpine:latest
WORKDIR /app
COPY --from=builder /bin/qbxpool /bin/qbxpool
COPY config.example.yaml /app/config.yaml
EXPOSE 3333
ENTRYPOINT ["/bin/qbxpool", "/app/config.yaml"]
